routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if (Auth::check()) {
		return view('home');
	}else{
		return view('auth.login');
	}
    
});


Route::get('/tentang', function () {
    return view('tentang');
});

Auth::routes();

/*Route::get('/edit/{id}', 'HomeController@edit')->name('editnama');
Route::put('/edit/{id}', 'HomeController@ubahnama')->name('ubahnama');*/
Route::resource('/user', 'HomeController');

//Route::get('/tentang', 'HomeController@tentang')->name('tentang');


Route::resource('/soal', 'SoalController');
Route::get('/soal/{pel}/{thn}', 'SoalController@showSoal')->name('showsoal');

Route::resource('/ujian', 'QuizController');
Route::get('/ujian/{pel}/{thn}', 'QuizController@showquiz')->name('showquiz');
Route::get('/hasil/{pel}/{thn}', 'QuizController@resultQuiz')->name('resultquiz');

Route::get('/home', 'QuizController@viewScore')->name('score');

/*Route::get('edit/{id}', ['as' => 'user.edit', 'uses' => 'HomeController@editUser']);
Route::patch('edit/{id}', ['as' => 'user.update', 'uses' => 'HomeController@update']);
*/
/*Route::group(['namespace' => 'User', 'prefix' => 'user'], function(){
    Route::get('{nickname}/settings', ['as' => 'user.settings', 'uses' => 'HomeController@edit']);
    Route::get('{nickname}/profile', ['as' => 'user.profile', 'uses' => 'HomeController@edit']);
});*/

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<div id="templatemo_wrapper">

      <div id="templatemo_content_wrapper">
        <span class="top"></span><span class="bottom"></span>
        <div id="templatemo_content">

          <h2>Home</h2>
          <p>Pro Teal Template is a full-site (5 pages) <a href="http://www.templatemo.com" target="_parent">website template</a> provided by
            <a href="http://www.templatemo.com" target="_parent">templatemo.com</a> and you may edit and apply this template for your websites. Credits go to
            <a href="http://www.photovaco.com" target="_blank">Free Photos</a> for photos and <a href="http://www.smashingmagazine.com" target="_blank">SmashingMagazine.com</a> for icons used in this template. Validate
            <a  href="http://validator.w3.org/check?uri=referer" rel="nofollow">XHTML</a> <a href="http://jigsaw.w3.org/css-validator/check/referer" rel="nofollow">CSS</a>.</p>
          <p>In ac libero urna. </p>


        </div> <!-- end -->

        <div id="templatemo_sidebar">

            

            <div class="cleaner"></div>
        </div>

      <div class="cleaner"></div>

      </div>

  </div>

    <!-- Scripts -->
    <script src="{{ asset('vendor/js/jquery-1.3.1.min.js') }}"></script>
    <script src="{{ asset('vendor/js/jquery.easing.1.3.js') }}"></script>
    <script src="{{ asset('vendor/js/jquery.ennui.contentslider.js') }}"></script>
    <script type="text/javascript">
        $(function() {
        $('#one').ContentSlider({
        width : '600px',
        height : '240px',
        speed : 600,
        easing : 'easeInOutQuart'
        });
        });
    </script>

@endsection

resources/views/home1.blade.php
@extends('layouts.app1')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card card-default">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/profile.blade.php
@extends('layouts.app')

@section('content')

<style>
	label{
		color: white;
	}
</style>

<img src="{{ URL::asset('images/uploads/'.Auth::user()->foto ) }}" style="width: 100px; float: right;">

  <h3>Ubah profile</h3>
  <form method="post" action="{{ route('user.update', $user->id) }}" enctype="multipart/form-data"> {{-- {{ route('edit.update', $user->id) }} --}}
    @csrf
    @method('put')

    <label>Nama</label> <br>
    <input type="text" name="nama" value="{{Auth::user()->name}}">
    <br><br>

    <label>Tempat lahir</label> <br>
    <input type="text" name="tempat_lahir" value="{{Auth::user()->tempat_lahir}}">
    <br><br>

    <label>Tanggal lahir</label> <br>
    <input type="date" name="tgl_lahir" value="{{Auth::user()->tgl_lahir}}">
    <br><br>

    <label>Alamat</label> <br>
    <textarea name="alamat">{{Auth::user()->alamat}}</textarea>
    <br><br>

    <label>Foto</label> <br>
    <input style="color: white;" type="file" class="" id="" name="foto">
	<br><br>


    <button type="submit" name="button">Ubah</button>
  </form>

@endsection

resources/views/result.blade.php
@extends('layouts.app')

@section('content')

<style>
	.quiz{
		background-color: white; 
		border-radius: 10px;
		padding: 10px;
	}
	/* Create two equal columns that floats next to each other */
	.column {
	    float: left;
	    width: 50%;
	}

	/* Clear floats after the columns */
	.row:after {
	    content: "";
	    display: table;
	    clear: both;
	}
	h2, h4, h6{
		color: white;
	}

	.green{
		color: green;
		font-weight: bold;
	}
	.red{
		color: red;
		font-weight: bold;
	}

</style>

<br><br>
<h2>Hasil</h2>
<h4>Ujian: {{$kategori}}</h4>
<h6>Tahun: {{$tahun}}</h6>


<form method="post" action="{{ route('ujian.store') }}">

@csrf
		@php $count = 0; @endphp


		@foreach($soals as $no=>$soal)

		<div class="quiz">

			<div class="row">
			  <div class="column" style="width: 3%;">
			  	<p>{{ ++$no }}</p>
			  </div>
			  <div class="column" style="width: 90%;">
			  	{!! $soal->soal !!}

			  	<input type="hidden" name="idSoal_{{$no}}" value="{{ $soal->id }}">



			  	<input @if($soal->jwbQuiz == "A") checked="checked" @endif value="A" type="radio" name="jwb_{{ $no }}" style="float: left; margin: 0; margin-right: 5px; margin-top: 3px;">
			  	<div @if($soal->jawaban == "A") class="green" @endif>
				  	<span style="float: left; margin: 0; margin-right: 5px;">A.</span>
					{!! $soal->pilihan_a !!}
				</div>

			  	<input @if($soal->jwbQuiz == "B") checked="checked" @endif value="B" type="radio" name="jwb_{{ $no }}" style="float: left; margin: 0; margin-right: 5px; margin-top: 3px;">
			  	<div @if($soal->jawaban == "B") class="green" @endif>
			  		<span style="float: left; margin: 0; margin-right: 5px;">B.</span>
					{!! $soal->pilihan_b !!}
				</div>

			  	<input @if($soal->jwbQuiz == "C") checked="checked" @endif value="C" type="radio" name="jwb_{{ $no }}" style="float: left; margin: 0; margin-right: 5px; margin-top: 3px;">
			  	<div @if($soal->jawaban == "C") class="green" @endif>
			  		<span style="float: left; margin: 0; margin-right: 5px;">C.</span>
					{!! $soal->pilihan_c !!}
				</div>

			  	<input @if($soal->jwbQuiz == "D") checked="checked" @endif value="D" type="radio" name="jwb_{{ $no }}" style="float: left; margin: 0; margin-right: 5px; margin-top: 3px;">
			  	<div @if($soal->jawaban == "D") class="green" @endif>
			  		<span style="float: left; margin: 0; margin-right: 5px;">D.</span>
					{!! $soal->pilihan_d !!}
				</div>

				Penjelasan:<br>
				{!! $soal->penjelasan !!}

				@if(empty($soal->penjelasan))
					<p>Penjelasan dengan gambar tidak tersedia</p>
				@else
					<img width="200px" src="{{ URL::asset('images/uploads/'.$soal->penjelasan_gambar ) }}">
				@endif

			  </div>
			</div>
			
			@php $count = $no; @endphp
			
		</div>

		<br>

		@endforeach

	@if($count == 0) 
		<br>
		<h3>Soal belum tersedia.</h3>
	@else
		<input type="hidden" name="count" value="{{ $count }}">
		<input type="hidden" name="kategori" value="{{ $kategori }}">
		<input type="hidden" name="tahun" value="{{ $tahun }}">
		
	@endif

	

</form>

<a style="color: white" href="{{url('/home')}}">Lihat score</a>

<br><br><br><br>


@endsection

resources/views/score.blade.php
@extends('layouts.app')

@section('content')

<style>
	.box{
		height: 300px;
		float: left;
		background-color: white;
		border-radius: 20px;
		margin: 10px;
	}
	h2, h4{
		color: white;
	}
</style>


@guest

informasi web


@else

<br><br>
<h2>Score:</h2>

@if($soals == null)
	<h4>Belum ada soal yang dikerjakan.</h4>
@endif

@foreach($soals as $no=>$soal) 

	@if($soal->kategori == null)

		<h4>Belum ada soal yang dikerjakan.</h4>

	@else

		<div class="box" style="width: 31%">
			<center><h1 style="padding: 10px; margin-top: 20px;">{{$soal->kategori}}</h1>
				<h6>{{$soal->tahun}}</h6></center>
			<br><br><br>
			<center><span style="font-size: 100px; margin-top: 100px;">{{$soal->score}}</span></center>
		</div>

	@endif

	
@endforeach



@endguest



@endsection

resources/views/soal.blade.php
@extends('layouts.app')

@section('content')

<style>
	h4, h6{
		color: white;
	}
</style>

<a href="{{url('soal/create')}}">Tambah Soal</a>

<br><br>

<h4>Soal : {{$soal}}</h4>
<h6>Tahun : {{$tahun}}</h6>

<table id="table">
	<tr>
		<th>No.</th>
		<th>Soal</th>
		<th>Pil. A</th>
		<th>Pil. B</th>
		<th>Pil. C</th>
		<th>Pil. D</th>
		<th>Pjlsn</th>
		<th>Pjlsn <br>Gambar</th>
		<th>Jwb</th>
		<th></th>
	</tr>
	
	@foreach($soals as $no=>$soal)
	<tr>
		<td>{{ ++$no }}</td>
		<td>{!! $soal->soal !!}</td>
		<td>{!! $soal->pilihan_a !!}</td>
		<td>{!! $soal->pilihan_b !!}</td>
		<td>{!! $soal->pilihan_c !!}</td>
		<td>{!! $soal->pilihan_d !!}</td>
		<td>{!! $soal->penjelasan !!}</td>
		<td>{{ $soal->penjelasan_gambar }}</td>
		<td>{{ $soal->jawaban }}</td>
		<td>
			<a href="{{ route('soal.edit', $soal->id) }}">Edit</a>
			<form id="form" onsubmit="return confirm('Yakin menghapus data?')" method="post" action="{{ route('soal.destroy', $soal->id) }}">
				@csrf
				@method('delete')
				{{-- <button type="submit">Hapus</button> --}}
				<a href="#" onclick="submit()">Hapus</a>
			</form>
			
		</td>
	</tr>
	@endforeach
	

</table>

<script>
	function submit(){
		$("#form").submit();
	}
</script>


@endsection

resources/views/soal_create.blade.php
@extends('layouts.app')

@section('content')



<div id="templatemo_content_wrapper">
	<span class="top"></span><span class="bottom"></span>
	<div id="templatemo_content">

		@if($errors->all())
			<span style="color: red">Data tidak boleh kosong.</span>
		@endif

		<form method="post" action="{{ route('soal.store') }}" enctype="multipart/form-data">

			@csrf

			<label>Kategori</label><br>
			<select name="kategori">
				<option value="{{ $pelajaran[0] }}">B. Indonesia</option>
				<option value="{{ $pelajaran[1] }}">Matematika</option>
				<option value="{{ $pelajaran[2] }}">IPA</option>
			</select>

			<br><br>
			<label>Tahun Ajaran</label><br>
			<select name="tahun">
				<option value="2015">2015</option>
				<option value="2016">2016</option>
				<option value="2017">2017</option>
				<option value="2018">2018</option>
			</select>

			<br><br>
			<label>Soal</label>
			<textarea required="" class="" name="soal" id="editor1" rows="8" cols="80" style="margin-bottom: 15px"></textarea>

			<br>
			<label>Pilihan A</label>
			<textarea required="" class="" name="pilihan_a" id="editor2" rows="8" cols="80" style="margin-bottom: 15px"></textarea>

			<br>
			<label>Pilihan B</label>
			<textarea required="" class="" name="pilihan_b" id="editor3" rows="8" cols="80" style="margin-bottom: 15px"></textarea>

			<br>
			<label>Pilihan C</label>
			<textarea required="" class="" name="pilihan_c" id="editor4" rows="8" cols="80" style="margin-bottom: 15px"></textarea>

			<br>
			<label>Pilihan D</label>
			<textarea required="" class="" name="pilihan_d" id="editor5" rows="8" cols="80" style="margin-bottom: 15px"></textarea>

			<br>
			<label>Penjelasan</label>
			<textarea required="" class="" name="penjelasan" id="editor6" rows="8" cols="80" style="margin-bottom: 15px"></textarea>

			<br>
			<label>Jawaban</label><br>
			<select name="jawaban">
				<option value="A">A</option>
				<option value="B">B</option>
				<option value="C">C</option>
				<option value="D">D</option>
			</select>

			<br><br>
			<label>Penjelasan dengan gambar</label> <br>
		    <input type="file" class="" id="" name="penjelasan_gambar">

			<br><br>
			<input type="submit" name="submit" value="Simpan">
			<input type="reset" name="clear" value="Reset">

		</form>
	</div>

	<div id="templatemo_sidebar">
		<a href="{{ url('/soal/create') }}">Buat Soal</a><br>
	</div>

	<div class="cleaner"></div>
</div>

<script src="{{ asset('vendor/ckeditor/ckeditor.js') }}"></script>
<script>
  CKEDITOR.replace( 'editor1' );
  CKEDITOR.replace( 'editor2' );
  CKEDITOR.replace( 'editor3' );
  CKEDITOR.replace( 'editor4' );
  CKEDITOR.replace( 'editor5' );
  CKEDITOR.replace( 'editor6' );
</script>


@endsection

resources/views/soal_edit.blade.php
@extends('layouts.app')

@section('content')



<div id="templatemo_content_wrapper">
	<span class="top"></span><span class="bottom"></span>
	<div id="templatemo_content">

		@if($errors->all())
			<span style="color: red">Data tidak boleh kosong.</span>
		@endif
		
		<form method="post" action="{{ route('soal.update', $soal->id) }}" enctype="multipart/form-data">

			@csrf
			@method('put')

			<label>Kategori</label><br>
			<select name="kategori">
				<option @if($soal->kategori == $pelajaran[0]) selected="selected" @endif value="{{$pelajaran[0]}}">Bahasa Indonesia</option>
				<option @if($soal->kategori == $pelajaran[1]) selected="selected" @endif value="{{$pelajaran[1]}}">Matematika</option>
				<option @if($soal->kategori == $pelajaran[2]) selected="selected" @endif value="{{$pelajaran[2]}}">IPA</option>
			</select>

			<br><br>
			<label>Tahun Ajaran</label><br>
			<select name="tahun">
				<option @if($soal->tahun == "2015") selected="selected" @endif value="2015">2015</option>
				<option @if($soal->tahun == "2016") selected="selected" @endif value="2016">2016</option>
				<option @if($soal->tahun == "2017") selected="selected" @endif value="2017">2017</option>
				<option @if($soal->tahun == "2018") selected="selected" @endif value="2018">2018</option>
			</select>

			<br><br>
			<label>Soal</label>
			<textarea class="" name="soal" id="editor1" rows="8" cols="80" style="margin-bottom: 15px">{{ $soal->soal }}</textarea>

			<br>
			<label>Pilihan A</label>
			<textarea class="" name="pilihan_a" id="editor2" rows="8" cols="80" style="margin-bottom: 15px">{{ $soal->pilihan_a }}</textarea>

			<br>
			<label>Pilihan B</label>
			<textarea class="" name="pilihan_b" id="editor3" rows="8" cols="80" style="margin-bottom: 15px">{{ $soal->pilihan_b }}</textarea>

			<br>
			<label>Pilihan C</label>
			<textarea class="" name="pilihan_c" id="editor4" rows="8" cols="80" style="margin-bottom: 15px">{{ $soal->pilihan_c }}</textarea>

			<br>
			<label>Pilihan D</label>
			<textarea class="" name="pilihan_d" id="editor5" rows="8" cols="80" style="margin-bottom: 15px">{{ $soal->pilihan_d }}</textarea>

			<br>
			<label>Penjelasan</label>
			<textarea class="" name="penjelasan" id="editor6" rows="8" cols="80" style="margin-bottom: 15px">{{ $soal->penjelasan }}</textarea>

			<br>
			<label>Jawaban {{$soal->jawaban}}</label><br>
			<select name="jawaban">
				<option @if($soal->jawaban == "A") selected="selected" @endif value="A">A</option>
				<option @if($soal->jawaban == "B") selected="selected" @endif value="B">B</option>
				<option @if($soal->jawaban == "C") selected="selected" @endif value="C">C</option>
				<option @if($soal->jawaban == "D") selected="selected" @endif value="D">D</option>
			</select>

			<br><br>
			<label>Penjelasan dengan gambar</label> <br>
		    <input type="file" class="" id="" name="penjelasan_gambar">

			<br><br>
			<input type="submit" name="submit" value="Simpan">
			<input type="reset" name="clear" value="Reset">

		</form>
	</div>

	<div id="templatemo_sidebar">
		<a href="{{ url('/soal/create') }}">Buat Soal</a><br>
		<a href="{{ url('/soal') }}">Lihat Soal</a>
	</div>

	<div class="cleaner"></div>
</div>

<script src="{{ asset('vendor/ckeditor/ckeditor.js') }}"></script>
<script>
  CKEDITOR.replace( 'editor1' );
  CKEDITOR.replace( 'editor2' );
  CKEDITOR.replace( 'editor3' );
  CKEDITOR.replace( 'editor4' );
  CKEDITOR.replace( 'editor5' );
  CKEDITOR.replace( 'editor6' );
</script>


@endsection

resources/views/tentang.blade.php
@extends('layouts.app')

@section('content')

<style>
  /* Create two equal columns that floats next to each other */
  .column {
      float: left;
      padding: 5px;
  }

  /* Clear floats after the columns */
  .row:after {
      content: "";
      display: table;
      clear: both;
  }
  h2, h4, h6{
    color: white;
  }

  .green{
    color: green;
    font-weight: bold;
  }
  .red{
    color: red;
    font-weight: bold;
  }

  .box{
    height: 250px;
    border-radius: 10px;
    background-color: #aae2da;
  }

  p{
    padding-left: 10px;
    padding-right: 10px;
  }

  h3 {
    padding: 10px;
    background-color: #4cbaaa;
    border-radius: 10px 10px 0px 0px;
  }

</style>



<div class="row">

  <div class="column" style="width: 48%">

    <div class="box">
      <h3>Title</h3>
      <p>Isinya</p>
    </div>

  </div>

  <div class="column" style="width: 48%; float: right;">
    <div class="box">
      <h3>Title</h3>
      <p>Isinya</p>
    </div>
  </div>

</div>

<div class="row">

  <div class="column" style="width: 48%">

    <div class="box">
      <h3>Title</h3>
      <p>Isinya</p>
    </div>

  </div>

  <div class="column" style="width: 48%; float: right;">
    <div class="box">
      <h3>Title</h3>
      <p>Isinya</p>
    </div>
  </div>

</div>

@endsection

resources/views/ujian.blade.php
@extends('layouts.app')

@section('content')

<style>
	.quiz{
		background-color: white; 
		border-radius: 10px;
		padding: 10px;
	}
	/* Create two equal columns that floats next to each other */
	.column {
	    float: left;
	    width: 50%;
	}

	/* Clear floats after the columns */
	.row:after {
	    content: "";
	    display: table;
	    clear: both;
	}
	h4, h6{
		color: white;
	}
</style>

<br><br>
<h4>Ujian: {{$kategori}}</h4>
<h6>Tahun: {{$tahun}}</h6>


<form method="post" action="{{ route('ujian.store') }}">

@csrf
		@php $count = 0; @endphp


		@foreach($soals as $no=>$soal)

		<div class="quiz">

			<div class="row">
			  <div class="column" style="width: 3%;">
			  	<p>{{ ++$no }}</p>
			  </div>
			  <div class="column" style="width: 90%;">
			  	{!! $soal->soal !!}

			  	<input type="hidden" name="idSoal_{{$no}}" value="{{ $soal->id }}">

			  	<input value="A" type="radio" name="jwb_{{ $no }}" style="float: left; margin: 0; margin-right: 5px; margin-top: 3px;">
			  	<span style="float: left; margin: 0; margin-right: 5px;">A.</span>
				{!! $soal->pilihan_a !!}

			  	<input value="B" type="radio" name="jwb_{{ $no }}" style="float: left; margin: 0; margin-right: 5px; margin-top: 3px;">
			  	<span style="float: left; margin: 0; margin-right: 5px;">B.</span>
				{!! $soal->pilihan_b !!}

			  	<input value="C" type="radio" name="jwb_{{ $no }}" style="float: left; margin: 0; margin-right: 5px; margin-top: 3px;">
			  	<span style="float: left; margin: 0; margin-right: 5px;">C.</span>
				{!! $soal->pilihan_c !!}

			  	<input value="D" type="radio" name="jwb_{{ $no }}" style="float: left; margin: 0; margin-right: 5px; margin-top: 3px;">
			  	<span style="float: left; margin: 0; margin-right: 5px;">D.</span>
				{!! $soal->pilihan_d !!}

			  </div>
			</div>
			
			@php $count = $no; @endphp
			
		</div>

		<br>

		@endforeach

	@if($count == 0) 
		<br>
		<h3>Soal belum tersedia.</h3>
	@else
		<input type="hidden" name="count" value="{{ $count }}">
		<input type="hidden" name="kategori" value="{{ $kategori }}">
		<input type="hidden" name="tahun" value="{{ $tahun }}">
		<input type="submit" name="Selesai" value="Selesai">
	@endif

	

</form>

<br><br><br><br>


@endsection